export const browserCoreExamples = [
  "hanzo-bot browser status",
  "hanzo-bot browser start",
  "hanzo-bot browser stop",
  "hanzo-bot browser tabs",
  "hanzo-bot browser open https://example.com",
  "hanzo-bot browser focus abcd1234",
  "hanzo-bot browser close abcd1234",
  "hanzo-bot browser screenshot",
  "hanzo-bot browser screenshot --full-page",
  "hanzo-bot browser screenshot --ref 12",
  "hanzo-bot browser snapshot",
  "hanzo-bot browser snapshot --format aria --limit 200",
  "hanzo-bot browser snapshot --efficient",
  "hanzo-bot browser snapshot --labels",
];

export const browserActionExamples = [
  "hanzo-bot browser navigate https://example.com",
  "hanzo-bot browser resize 1280 720",
  "hanzo-bot browser click 12 --double",
  'openclaw browser type 23 "hello" --submit',
  "hanzo-bot browser press Enter",
  "hanzo-bot browser hover 44",
  "hanzo-bot browser drag 10 11",
  "hanzo-bot browser select 9 OptionA OptionB",
  "hanzo-bot browser upload /tmp/openclaw/uploads/file.pdf",
  'openclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "hanzo-bot browser dialog --accept",
  'openclaw browser wait --text "Done"',
  "hanzo-bot browser evaluate --fn '(el) => el.textContent' --ref 7",
  "hanzo-bot browser console --level error",
  "hanzo-bot browser pdf",
];
